### ISSUE TITLE
undefined method `zmq_ctx_term' for LibZMQ:Module

### ISSUE THREAD

**Issue by andyroberts** [chuckremes/ffi-rzmq-core#17]
This issue relates to using ffi-rzmq on a system with libzmq3 installed (v3.2.5), although ultimately trickles down to ffi-rzmq-core hence why I'm posting here.

I'm calling `context.terminate` but getting the following exception:

    NoMethodError: undefined method `zmq_ctx_term' for LibZMQ:Module

I notice this commit https://github.com/chuckremes/ffi-rzmq/commit/7aa7bec863ea5b7524ab1c5194129534ab13667d which sees `LibZMQ.zmq_ctx_destroy()` removed in favour of `LibZMQ.zmq_ctx_term()`.

However, I can't see the corresponding method, in ffi-rzmq-core, just the older zmq_ctx_destroy. See https://github.com/chuckremes/ffi-rzmq-core/blob/master/lib/ffi-rzmq-core/libzmq.rb#L90

I note that the function is attached in libzmq4.rb: https://github.com/chuckremes/ffi-rzmq-core/blob/master/lib/ffi-rzmq-core/libzmq4.rb#L5

Would this explain why I'm seeing the undefined method?

**Comment by chuckremes** [comment]
Yes, you are correct. The commit you listed above apparently broke compatibility with libzmq version 3.x.

You have a few options here.

1. Upgrade to libzmq 4.x. I checked the history and libzmq 3.2.5 was released in October 2014.
2. Downgrade the ffi-rzmq gem to version 2.0.4.
3. Hand edit the ffi-rzmq 2.0.5 gem to reverse that commit that replaced `zmq_term` and `zmq_ctx_destroy` with `zmq_ctx_term`.
4. Figure out a permanent fix for ffi-rzmq that will support both libzmq3 and libzmq4 and send me a pull request. I will happily merge it.
